### ISSUE TITLE
Need to account for new launcher versions

### ISSUE THREAD

**Issue by Dekubaka** [Dekubaka/TDMPAuto#1]
The TDMP Launcher currently does not auto-update to the next launcher version.

So this script will need to look for and remove older launcher versions so there are not multiple in the documents folder. Then it needs to redirect the desktop shortcut to the newest version.

**Comment by Dekubaka** [comment]
TDMP team made an auto update launcher so I will adjust the code to pull that launcher instead of the current.

https://github.com/TDMP-Team/TDMP-Launcher-Updater-Public/releases/tag/0.1.0

**Comment by TTFH** [comment]
> TDMP team made an auto update launcher so I will adjust the code to pull that launcher instead of the current.

You can also rename this repository to "TDMP Launcher Updater Downloader" for the lols

**Comment by Dekubaka** [comment]
Got the flu for my Christmas & new years gift, so finally tackled this.

Also, name changed approved!
